"""任务模块抽象端口层：读取、可靠命令、同步恢复原型和 Progress 边界。"""

from .callback_recovery import (
    CallbackRecoveryPort,
    CallbackRecoveryResult,
    DELIVERY_OUTCOME_UNKNOWN,
)
from .callback_recovery_commands import (
    CALLBACK_RECOVERY_COMMAND_SCHEMA_VERSION,
    CALLBACK_RECOVERY_TRIGGER_CHECK_TASK,
    CallbackRecoveryCommand,
    CallbackRecoveryCommandOutcome,
    CallbackRecoveryCommandPort,
    CallbackRecoveryCommandResult,
)
from .callback_delivery_control import (
    CallbackAdmissionConflict,
    CallbackAdmissionConflictPort,
)
from .clock import ClockAnomalyError, ClockPort, require_persisted_utc
from .progress import (
    GuardedProgressPublisherPort,
    ProgressPublication,
    ProgressPublisherPort,
    ProgressSnapshotPort,
    ProgressSubscriber,
    ProgressSubscription,
    ProgressSubscriptionPort,
)
from .task_commands import (
    ExpectedProgressUpdate,
    ExpectedTaskCompletion,
    TaskClaimOutcome,
    TaskClaimResult,
    TaskCommandPort,
    TaskSubmissionCommand,
    TaskSubmissionOutcome,
    TaskSubmissionResult,
)
from .task_read import TaskReadPort
from .task_queue import TaskQueueInspectionPort, TaskQueueSnapshot
from .task_codec import EncodedTaskResult, EncodedTaskSubmission, TaskCommandCodec
from .task_admission import (
    TaskAdmissionOutcome,
    TaskAdmissionPort,
    TaskAdmissionRequest,
    TaskAdmissionResult,
    validate_task_admission_batch,
)
from .task_events import TaskEventQueryPort
from .task_execution import (
    TaskClaimRequest,
    TaskExecutionClaimResult,
    TaskExecutionMutationOutcome,
    TaskExecutionPort,
    TaskHeartbeatCommand,
    TaskHeartbeatResult,
    TaskProgressCommand,
    TaskRunnableQueryPort,
    TaskStepCompletionCommand,
    TaskStepIntentCommand,
    TaskStepSkipCommand,
    TaskTerminalCommand,
)
from .task_recovery import (
    TaskRecoveryClaimRequest,
    TaskRecoveryClaimResult,
    TaskRecoveryClassificationCommand,
    TaskRecoveryClassificationResult,
    TaskRecoveryHeartbeatCommand,
    TaskRecoveryHeartbeatResult,
    TaskRecoveryMutationOutcome,
    TaskRecoveryOperationIntentCommand,
    TaskRecoveryPolicyPort,
    TaskRecoveryPort,
)
from .unit_of_work import (
    TaskAdmissionUnitOfWork,
    TaskAdmissionUnitOfWorkFactory,
    TaskExecutionUnitOfWork,
    TaskExecutionUnitOfWorkFactory,
    TaskRecoveryUnitOfWork,
    TaskRecoveryUnitOfWorkFactory,
)
from .runtime import (
    LeaseHeartbeatSupervisorPort,
    LeaseSupervisorOutcome,
    LeaseSupervisorResult,
    LocalMaintenanceSchedulerPort,
    LocalTaskExecutorPort,
    ProcessSingletonGuardPort,
    TaskExecutionPermitPort,
    TaskExecutionRuntimePort,
)

__all__ = [
    "CALLBACK_RECOVERY_COMMAND_SCHEMA_VERSION",
    "CALLBACK_RECOVERY_TRIGGER_CHECK_TASK",
    "CallbackAdmissionConflict",
    "CallbackAdmissionConflictPort",
    "CallbackRecoveryCommand",
    "CallbackRecoveryCommandOutcome",
    "CallbackRecoveryCommandPort",
    "CallbackRecoveryCommandResult",
    "CallbackRecoveryPort",
    "CallbackRecoveryResult",
    "ClockAnomalyError",
    "ClockPort",
    "DELIVERY_OUTCOME_UNKNOWN",
    "ExpectedProgressUpdate",
    "ExpectedTaskCompletion",
    "EncodedTaskResult",
    "EncodedTaskSubmission",
    "GuardedProgressPublisherPort",
    "LeaseHeartbeatSupervisorPort",
    "LeaseSupervisorOutcome",
    "LeaseSupervisorResult",
    "LocalMaintenanceSchedulerPort",
    "LocalTaskExecutorPort",
    "ProgressPublication",
    "ProgressPublisherPort",
    "ProgressSnapshotPort",
    "ProgressSubscriber",
    "ProgressSubscription",
    "ProgressSubscriptionPort",
    "ProcessSingletonGuardPort",
    "TaskReadPort",
    "TaskClaimOutcome",
    "TaskClaimResult",
    "TaskClaimRequest",
    "TaskCommandCodec",
    "TaskCommandPort",
    "TaskAdmissionOutcome",
    "TaskAdmissionPort",
    "TaskAdmissionRequest",
    "TaskAdmissionResult",
    "TaskAdmissionUnitOfWork",
    "TaskAdmissionUnitOfWorkFactory",
    "TaskEventQueryPort",
    "TaskExecutionClaimResult",
    "TaskExecutionMutationOutcome",
    "TaskExecutionPort",
    "TaskQueueInspectionPort",
    "TaskQueueSnapshot",
    "TaskExecutionPermitPort",
    "TaskExecutionRuntimePort",
    "TaskExecutionUnitOfWork",
    "TaskExecutionUnitOfWorkFactory",
    "TaskHeartbeatCommand",
    "TaskHeartbeatResult",
    "TaskProgressCommand",
    "TaskRecoveryClaimRequest",
    "TaskRecoveryClaimResult",
    "TaskRecoveryClassificationCommand",
    "TaskRecoveryClassificationResult",
    "TaskRecoveryHeartbeatCommand",
    "TaskRecoveryHeartbeatResult",
    "TaskRecoveryMutationOutcome",
    "TaskRecoveryOperationIntentCommand",
    "TaskRecoveryPolicyPort",
    "TaskRecoveryPort",
    "TaskRecoveryUnitOfWork",
    "TaskRecoveryUnitOfWorkFactory",
    "TaskRunnableQueryPort",
    "TaskStepCompletionCommand",
    "TaskStepIntentCommand",
    "TaskStepSkipCommand",
    "TaskSubmissionCommand",
    "TaskSubmissionOutcome",
    "TaskSubmissionResult",
    "TaskTerminalCommand",
    "require_persisted_utc",
    "validate_task_admission_batch",
]
