"""报告业务模块的正式公开入口。

阶段 1C-2 公开纯领域 DTO/规则以及 Submit/Run 应用入口。端口通过 ``report.ports``
子包公开，具体基础设施实现不得从本包根目录导出。
"""

from .application import (
    ReportTaskCompletion,
    RunReportOutcome,
    RunReportResult,
    RunReportTask,
    SubmitReportResult,
    SubmitReportTask,
)

from .domain import (
    EMPTY_REPORT_HTML,
    REPORT_STATUS_FAILED,
    REPORT_STATUS_SUCCEEDED,
    ReportArtifactError,
    ReportAuditError,
    ReportCallbackError,
    ReportCleanupError,
    ReportCallbackPayload,
    ReportDomainValidationError,
    ReportError,
    ReportId,
    ReportInputError,
    ReportInputSnapshot,
    ReportRagError,
    ReportPortContractError,
    ReportSourceNormalizationError,
    ReportResult,
    ReportStaleExecutionError,
    ReportSubmission,
    ReportTaskConflictError,
    ReportTaskPersistenceError,
    ReportTemplateError,
    build_report_callback,
    build_report_context_name,
    build_report_conversation_name,
    build_report_prompt,
    build_report_result,
    ensure_report_html,
)

__all__ = [
    "EMPTY_REPORT_HTML",
    "REPORT_STATUS_FAILED",
    "REPORT_STATUS_SUCCEEDED",
    "ReportArtifactError",
    "ReportAuditError",
    "ReportCallbackError",
    "ReportCleanupError",
    "ReportCallbackPayload",
    "ReportDomainValidationError",
    "ReportError",
    "ReportId",
    "ReportInputError",
    "ReportInputSnapshot",
    "ReportRagError",
    "ReportPortContractError",
    "ReportSourceNormalizationError",
    "ReportTaskCompletion",
    "ReportResult",
    "ReportStaleExecutionError",
    "ReportSubmission",
    "ReportTaskConflictError",
    "ReportTaskPersistenceError",
    "ReportTemplateError",
    "RunReportOutcome",
    "RunReportResult",
    "RunReportTask",
    "SubmitReportResult",
    "SubmitReportTask",
    "build_report_callback",
    "build_report_context_name",
    "build_report_conversation_name",
    "build_report_prompt",
    "build_report_result",
    "ensure_report_html",
]
